### PR TITLE
Moving code to TypeScript

### PR DESCRIPTION
**Pull request by lesyk**

### CODE REVIEW

**Comment by bilby91** [comment]
@lesyk Thanks for the contribution. 

This library will be deprecated in favor of https://github.com/suttna/botbuilder-slack. This library is intended for running you bot directly to Slack instead of BotFramework. It should work out of the box with your ChatConnector implementation. Either way I think it would be a good idea to be able to use library as an extension for the events that are missing when you use BotFramework.

**Comment by lesyk** [comment]
May you than share/give access (to this repo, or npm package) to me?
I will try to support this repo/package.

**Comment by bilby91** [comment]
@lesyk I think it would be a better idea to make `botbuilder-slack` work with the `ChatConnector` implementation. 

Either way, feel free to fork and use the code as you want :)

**Comment by bilby91** [comment]
@lesyk If you are interested in my last comment I can help BTW.

**Comment by bilby91** [comment]
@lesyk Have you tried using `botbuilder-slack` ? After thinking a little bit more on your use case, I'm pretty confident that you should be able to use it without issues. 

Let me know if I can help you with the testing. Will be closing this PR and the other issues.

Thanks.

**Pull request closed without merging**
